### ISSUE TITLE
Idea: Extend flag to extend sample data based on existing data

### ISSUE THREAD

**Issue by FrediBach** [hasura/json2graphql#5]
Ok, this is something that has zero priority, but I think it would be something very useful, I may even make a pull request for it someday.

Let's say we have this sample data:

```
module.exports = {
    posts: [
        { id: 1, title: "Lorem Ipsum", views: 254, created: "2018-03-02T12:00:00+01:45", user_id: 123 },
        { id: 2, title: "Sic Dolor amet", views: 65, created: "2018-05-22T12:00:00+08:54", user_id: 456 },
        { id: 3, title: "Long sample text, that sets limit for maximum text length.", views: 2, created: "2018-08-23T12:00:00+11:11", user_id: 456 },
    ],
    users: [
        { id: 123, name: "John Doe" },
        { id: 456, name: "Jane Doe" }
    ]
}
```

By just that sample data, we can "guess" quite a few things:

- A user can have multiple posts
- View counts range between 2 and 254
- Text length for the title is somewhere between 10 and 64 characters long
- The created date is between March 2018 and August 2018
- Name is probably hard to detect, but not impossible

Knowing all that, we could automatically generate additional sample data, like a lot of additional data. This would make it possible to implement features in the app like a paginated list, that would be hard to do with just handwritten sample data, as that would be way to time consuming to write. And with a lot of variability in text lengths, styling issues caused by such variable data could be detected much earlier.

**Comment by FrediBach** [comment]
A first early version of this idea already works quite nicely: https://github.com/FrediBach/json-data-extender

I've tested the data import with the extended sample data in that repo, and was surprised how fast it imported that almost 1MB of data into Hasura, with thousands of entries and even more relationships. Nice work! :-)

**Comment by wawhal** [comment]
This repo has been moved.
This issue is tracked [here](https://github.com/hasura/graphql-engine/issues/467).
